/**
 * Outdoor-living services. Each entry becomes its own SEO landing page at
 * /services/[slug]. A null image renders a placeholder until a matching photo exists.
 * Order follows the sequence Brandon walks clients through on a call.
 */
export const services = [
    {
        slug: "paver-patios",
        name: "Paver Patios",
        short: "Unilock and Techo-Bloc paver patios engineered to stay level and beautiful for years.",
        tileImage: "/project-photos/paver-patios--herringbone-walkway-patio-fire-pit-seat-wall.jpg",
        heroImage: "/project-photos/paver-patios--raised-patio-curved-seat-wall-pillars.webp",
        intro: "Our paver patios are built on a proper base so they stay level and beautiful for years. We work with premium manufacturers like Unilock and Techo-Bloc to create outdoor spaces perfect for entertaining, dining, or simply relaxing.",
        highlights: [
            "Unilock & Techo-Bloc authorized installation",
            "Seat walls, steps, and retaining walls",
            "Fire features and built-in seating",
            "Proper base preparation and drainage",
        ],
        featured: true,
    },
    {
        slug: "composite-decks",
        name: "Custom Decks",
        short: "Low-maintenance composite decks proportioned to your home and built to last decades.",
        tileImage: "/project-photos/custom-decks--aerial-multi-level-deck-privacy-panels-stairs.webp",
        heroImage: "/project-photos/custom-decks--composite-deck-wide-lit-stairs-planter-boxes.webp",
        intro: "A custom deck is the foundation of most backyard transformations. We design every deck around how you actually want to use the space — entertaining, dining, relaxing — and build it in premium, low-maintenance composite materials that age as gracefully as they photograph.",
        highlights: [
            "TimberTech & Deckorators composite decking",
            "Aluminum and composite railing systems",
            "Multi-level decks, stairs, and built-in seating",
            "Integrated low-voltage lighting",
        ],
        featured: true,
    },
    {
        slug: "fencing",
        name: "Fencing",
        short: "Privacy, security, and style that ties the whole yard together.",
        tileImage: "/project-photos/fencing--white-vinyl-privacy-fence-yard.webp",
        heroImage: "/project-photos/fencing--wood-privacy-fence-with-gate-backyard.webp",
        intro: "The right fence adds privacy, security, and a finished look to your property. We install a range of fence styles designed to complement your outdoor living space and your home.",
        highlights: [
            "Privacy, picket, and decorative styles",
            "Premium, low-maintenance materials",
            "Gates and access features",
            "Coordinated design with your full project",
        ],
        featured: true,
    },
    {
        slug: "pergolas-pavilions",
        name: "Pergolas & Pavilions",
        short: "Shade and architecture that frame the yard and temper the afternoon sun.",
        tileImage: "/project-photos/pergolas-pavilions--timber-pavilion-paver-patio-fire-pit-seat-wall.webp",
        heroImage: "/project-photos/pergolas-pavilions--white-vinyl-pergola-paver-patio-fire-pit.webp",
        intro: "Pergolas and pavilions bring shade, structure, and a sense of destination to your backyard. We design them to feel like they were always part of your home.",
        highlights: [
            "Custom-designed pergolas and pavilions",
            "Premium wood and low-maintenance materials",
            "Privacy walls and integrated lighting",
            "Sized and detailed to match your home",
        ],
        featured: true,
    },
    {
        slug: "louvered-pavilions",
        name: "Louvered Pavilions",
        short: "Adjustable louvered roofs that let you dial in sun, shade, and shelter on demand.",
        tileImage: null,
        heroImage: null,
        intro: "A louvered pavilion gives you control over your backyard in a way a fixed roof can't. Open the louvers for full sun, angle them for filtered shade, or close them completely when the weather turns. We work with several manufacturers so we can match the right system to your space and budget.",
        highlights: [
            "Adjustable louvered roof systems",
            "Multiple manufacturers to choose from",
            "Motorized and remote-operated options",
            "Integrated lighting, fans, and heaters",
        ],
        featured: true,
    },
    {
        slug: "fireplaces-fire-pits",
        name: "Fire Features",
        short: "Gas and wood fire features that make the space usable long into the evening.",
        tileImage: "/project-photos/fire-features--gas-fire-table-night-paver-patio.webp",
        heroImage: "/project-photos/fire-features--stone-outdoor-fireplace-wood-storage.webp",
        intro: "Nothing extends an evening outside like a fire feature. We build gas and wood-burning fireplaces and fire pits that become the natural gathering point of your backyard.",
        highlights: [
            "Gas and wood-burning options",
            "Custom stone and paver surrounds",
            "Built-in seating integration",
            "Safe, code-compliant installation",
        ],
        featured: true,
    },
    {
        slug: "outdoor-kitchens",
        name: "Outdoor Kitchens",
        short: "Full outdoor kitchens that turn your backyard into the entertainment hub.",
        tileImage: "/project-photos/outdoor-kitchens--l-shaped-stone-kitchen-grill-sink-paver-patio.webp",
        heroImage: "/project-photos/outdoor-kitchens--covered-outdoor-kitchen-bar-white-columns.webp",
        intro: "Transform your backyard into an entertainment hub with a custom outdoor kitchen. We design and build everything from a simple grill station to a fully equipped kitchen with countertops, storage, and appliances.",
        highlights: [
            "Built-in grills, burners, and appliances",
            "Granite and stone countertops",
            "Weatherproof cabinetry and storage",
            "Bar seating and serving areas",
        ],
        featured: true,
    },
    {
        slug: "landscape-lighting",
        name: "Landscape Lighting",
        short: "Low-voltage lighting that makes your backyard usable and beautiful after dark.",
        tileImage: "/project-photos/custom-decks--elevated-deck-white-railing-post-cap-lights-night.webp",
        heroImage: "/project-photos/custom-decks--lit-composite-stairs-cable-railing-dusk.webp",
        intro: "Low-voltage landscape and hardscape lighting extends how long you can enjoy your space and highlights the craftsmanship of the project. We design lighting as part of the overall plan, not an afterthought.",
        highlights: [
            "Deck, step, and railing lighting",
            "Hardscape and path lighting",
            "Accent and feature lighting",
            "Energy-efficient low-voltage systems",
        ],
        featured: false,
    },
    {
        slug: "drainage",
        name: "Drainage",
        short: "Grading and drainage that protect your investment and keep the yard usable.",
        tileImage: null,
        heroImage: null,
        intro: "Water is the fastest way to ruin a beautiful backyard. We solve standing water, soggy lawns, and runoff against the foundation with proper grading and drainage — designed into the project from the start rather than patched in afterward.",
        highlights: [
            "French drains and dry wells",
            "Downspout and surface water management",
            "Regrading for positive drainage",
            "Drainage engineered into every hardscape",
        ],
        featured: false,
    },
    {
        slug: "landscaping",
        name: "Landscaping",
        short: "Planting and softscape that finish the project and settle it into the yard.",
        tileImage: "/project-photos/landscaping--flagstone-gravel-path-boulders-covered-porch.jpg",
        heroImage: "/project-photos/landscaping--flagstone-gravel-bed-boulders-steel-edging.jpg",
        intro: "Landscaping is what makes a new deck or patio look like it belongs. We finish projects with planting beds, trees, and softscape chosen for your light, soil, and how much upkeep you actually want.",
        highlights: [
            "Planting beds, trees, and shrubs",
            "Mulch, edging, and bed definition",
            "Low-maintenance plant selection",
            "Designed alongside the hardscape",
        ],
        featured: false,
    },
    {
        slug: "covered-outdoor-living",
        name: "Covered Outdoor Living",
        short: "Roofed structures that let you enjoy your backyard in every season.",
        tileImage: "/project-photos/covered-outdoor-living--gable-porch-cover-cedar-posts-stone-bases.webp",
        heroImage: "/project-photos/covered-outdoor-living--covered-deck-gable-roof-white-columns.webp",
        intro: "Covered outdoor living structures extend your season and turn a deck or patio into a true room. From attached roof structures to freestanding pavilions, we design them to match your home's architecture.",
        highlights: [
            "Attached and freestanding roof structures",
            "Tongue-and-groove and beadboard ceilings",
            "Integrated lighting, fans, and heaters",
            "TV walls and entertainment features",
        ],
        featured: true,
    },
    {
        slug: "screen-rooms",
        name: "Screen Rooms",
        short: "Finished, screened rooms open to the garden and comfortable all season.",
        tileImage: "/project-photos/screen-rooms--elevated-screened-porch-cedar-gable-black-railing.webp",
        heroImage: "/project-photos/screen-rooms--screened-porch-white-stairs.webp",
        intro: "A screen room gives you all the benefits of being outside with none of the bugs. We build finished, screened spaces that feel like a natural extension of your home.",
        highlights: [
            "Custom screen enclosures",
            "Finished ceilings and lighting",
            "Optional fireplaces and fans",
            "Seamless integration with decks and patios",
        ],
        featured: true,
    },
    {
        slug: "complete-backyard-transformations",
        name: "Complete Backyard Transformations",
        short: "One team managing your entire outdoor project — deck, patio, roof, kitchen, fire, lighting, and fence.",
        tileImage: "/project-photos/backyard-transformations--aerial-paver-patio-fire-pit-dining-pavilion.webp",
        heroImage: "/project-photos/backyard-transformations--paver-patio-outdoor-fireplace-kitchen-dining.jpg",
        intro: "This is where PDF Builders is different. Instead of hiring a deck guy, a patio guy, and a landscaper, you work with one team that designs and manages your entire outdoor project — deck, patio, pavilion, outdoor kitchen, fire features, lighting, and fencing — all under one contractor.",
        highlights: [
            "One contractor for the entire project",
            "Cohesive design across every element",
            "Single point of communication",
            "Permits, inspections, and scheduling handled for you",
        ],
        featured: true,
        isTransformation: true,
    },
];

export const getServiceBySlug = (slug) => services.find((s) => s.slug === slug);
