/**
 * Outdoor-living services. Each entry becomes its own SEO landing page at
 * /services/[slug]. Images are placeholders until real project photos arrive.
 */
export const services = [
    {
        slug: "composite-decks",
        name: "Composite Decks",
        short: "Low-maintenance composite decks proportioned to your home and built to last decades.",
        tileImage: "/projects/placeholder-deck.jpg",
        heroImage: "/projects/placeholder-deck.jpg",
        intro: "A custom deck is the foundation of most backyard transformations. We design every deck around how you actually want to use the space — entertaining, dining, relaxing — and build it in premium, low-maintenance composite materials that age as gracefully as they photograph.",
        highlights: [
            "TimberTech & Deckorators composite decking",
            "Aluminum and composite railing systems",
            "Multi-level decks, stairs, and built-in seating",
            "Integrated low-voltage lighting",
        ],
        featured: true,
    },
    {
        slug: "paver-patios",
        name: "Paver Patios",
        short: "Unilock and Techo-Bloc paver patios engineered to stay level and beautiful for years.",
        tileImage: "/projects/placeholder-patio.jpg",
        heroImage: "/projects/placeholder-patio.jpg",
        intro: "Our paver patios are built on a proper base so they stay level and beautiful for years. We work with premium manufacturers like Unilock and Techo-Bloc to create outdoor spaces perfect for entertaining, dining, or simply relaxing.",
        highlights: [
            "Unilock & Techo-Bloc authorized installation",
            "Seat walls, steps, and retaining walls",
            "Fire features and built-in seating",
            "Proper base preparation and drainage",
        ],
        featured: true,
    },
    {
        slug: "covered-outdoor-living",
        name: "Covered Outdoor Living",
        short: "Roofed structures that let you enjoy your backyard in every season.",
        tileImage: "/projects/placeholder-covered.jpg",
        heroImage: "/projects/placeholder-covered.jpg",
        intro: "Covered outdoor living structures extend your season and turn a deck or patio into a true room. From attached roof structures to freestanding pavilions, we design them to match your home's architecture.",
        highlights: [
            "Attached and freestanding roof structures",
            "Tongue-and-groove and beadboard ceilings",
            "Integrated lighting, fans, and heaters",
            "TV walls and entertainment features",
        ],
        featured: true,
    },
    {
        slug: "screen-rooms",
        name: "Screen Rooms",
        short: "Finished, screened rooms open to the garden and comfortable all season.",
        tileImage: "/projects/placeholder-screen-room.jpg",
        heroImage: "/projects/placeholder-screen-room.jpg",
        intro: "A screen room gives you all the benefits of being outside with none of the bugs. We build finished, screened spaces that feel like a natural extension of your home.",
        highlights: [
            "Custom screen enclosures",
            "Finished ceilings and lighting",
            "Optional fireplaces and fans",
            "Seamless integration with decks and patios",
        ],
        featured: true,
    },
    {
        slug: "pergolas-pavilions",
        name: "Pergolas & Pavilions",
        short: "Shade and architecture that frame the yard and temper the afternoon sun.",
        tileImage: "/projects/placeholder-pergola.jpg",
        heroImage: "/projects/placeholder-pergola.jpg",
        intro: "Pergolas and pavilions bring shade, structure, and a sense of destination to your backyard. We design them to feel like they were always part of your home.",
        highlights: [
            "Custom-designed pergolas and pavilions",
            "Louvered roof options for sun and shade control",
            "Premium wood and low-maintenance materials",
            "Integrated lighting and privacy walls",
        ],
        featured: true,
    },
    {
        slug: "outdoor-kitchens",
        name: "Outdoor Kitchens",
        short: "Full outdoor kitchens that turn your backyard into the entertainment hub.",
        tileImage: "/projects/placeholder-outdoor-kitchen.jpg",
        heroImage: "/projects/placeholder-outdoor-kitchen.jpg",
        intro: "Transform your backyard into an entertainment hub with a custom outdoor kitchen. We design and build everything from a simple grill station to a fully equipped kitchen with countertops, storage, and appliances.",
        highlights: [
            "Built-in grills, burners, and appliances",
            "Granite and stone countertops",
            "Weatherproof cabinetry and storage",
            "Bar seating and serving areas",
        ],
        featured: true,
    },
    {
        slug: "fireplaces-fire-pits",
        name: "Fireplaces & Fire Pits",
        short: "Gas and wood fire features that make the space usable long into the evening.",
        tileImage: "/projects/placeholder-fire.jpg",
        heroImage: "/projects/placeholder-fire.jpg",
        intro: "Nothing extends an evening outside like a fire feature. We build gas and wood-burning fireplaces and fire pits that become the natural gathering point of your backyard.",
        highlights: [
            "Gas and wood-burning options",
            "Custom stone and paver surrounds",
            "Built-in seating integration",
            "Safe, code-compliant installation",
        ],
        featured: true,
    },
    {
        slug: "fencing",
        name: "Fencing",
        short: "Privacy, security, and style that ties the whole yard together.",
        tileImage: "/projects/placeholder-fence.jpg",
        heroImage: "/projects/placeholder-fence.jpg",
        intro: "The right fence adds privacy, security, and a finished look to your property. We install a range of fence styles designed to complement your outdoor living space and your home.",
        highlights: [
            "Privacy, picket, and decorative styles",
            "Premium, low-maintenance materials",
            "Gates and access features",
            "Coordinated design with your full project",
        ],
        featured: true,
    },
    {
        slug: "landscape-lighting",
        name: "Landscape Lighting",
        short: "Low-voltage lighting that makes your backyard usable and beautiful after dark.",
        tileImage: "/projects/placeholder-lighting.jpg",
        heroImage: "/projects/placeholder-lighting.jpg",
        intro: "Low-voltage landscape and hardscape lighting extends how long you can enjoy your space and highlights the craftsmanship of the project. We design lighting as part of the overall plan, not an afterthought.",
        highlights: [
            "Deck, step, and railing lighting",
            "Hardscape and path lighting",
            "Accent and feature lighting",
            "Energy-efficient low-voltage systems",
        ],
        featured: false,
    },
    {
        slug: "complete-backyard-transformations",
        name: "Complete Backyard Transformations",
        short: "One team managing your entire outdoor project — deck, patio, roof, kitchen, fire, lighting, and fence.",
        tileImage: "/projects/placeholder-transformation.jpg",
        heroImage: "/projects/placeholder-transformation.jpg",
        intro: "This is where PDF Builders is different. Instead of hiring a deck guy, a patio guy, and a landscaper, you work with one team that designs and manages your entire outdoor project — deck, patio, pavilion, outdoor kitchen, fire features, lighting, and fencing — all under one contractor.",
        highlights: [
            "One contractor for the entire project",
            "Cohesive design across every element",
            "Single point of communication",
            "Permits, inspections, and scheduling handled for you",
        ],
        featured: true,
        isTransformation: true,
    },
];

export const getServiceBySlug = (slug) => services.find((s) => s.slug === slug);
